package store;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class Political {
    public LinkedHashMap data() {
        LinkedHashMap<String, String> map = new LinkedHashMap<>();

        map.put("What is Democracy?", "A system where people elect their leaders.");
        map.put("What is a Republic?", "A government where the head of state is elected.");
        map.put("What is Socialism?", "An economic system where the government controls major industries.");
        map.put("What is Communism?", "A political system advocating classless society.");
        map.put("What is Capitalism?", "An economic system based on private ownership.");
        map.put("What is Fascism?", "A far-right, authoritarian government system.");
        map.put("What is a Constitution?", "A set of fundamental laws governing a nation.");
        map.put("What is a Parliament?", "The legislative body of a country.");
        map.put("What is a President?", "The head of state in a republic.");
        map.put("What is a Prime Minister?", "The head of government in a parliamentary system.");
        map.put("What is an Election?", "A process where people vote to choose leaders.");
        map.put("What is a Political Party?", "An organized group aiming to gain political power.");
        map.put("What is a Monarchy?", "A government where a king or queen rules.");
        map.put("What is a Dictatorship?", "A government ruled by one person with total power.");
        map.put("What is a Coalition Government?", "A government formed by multiple political parties.");
        map.put("What is a Vote of No Confidence?", "A parliamentary vote to remove a government.");
        map.put("What is a Veto?", "The power to reject a decision or proposal.");
        map.put("What is a Referendum?", "A direct vote by citizens on an issue.");
        map.put("What is Federalism?", "A system where power is divided between central and state governments.");
        map.put("What is a Bill?", "A proposed law presented in the legislature.");
        map.put("What is a Law?", "A set of rules enforced by the government.");
        map.put("What is an Amendment?", "A change or addition to the constitution.");
        map.put("What is a Legislature?", "A body responsible for making laws.");
        map.put("What is the Judiciary?", "The branch of government that interprets laws.");
        map.put("What is the Executive?", "The branch of government that enforces laws.");
        map.put("What is a Cabinet?", "A group of ministers advising the head of government.");
        map.put("What is a Governor?", "The head of a state in a federal system.");
        map.put("What is a Mayor?", "The elected head of a city or town.");
        map.put("What is Public Policy?", "Government actions to address public issues.");
        map.put("What is an Ideology?", "A system of beliefs influencing political views.");
        map.put("What is Nationalism?", "A political ideology promoting national identity.");
        map.put("What is Globalization?", "The increasing interconnection of the world.");
        map.put("What is Populism?", "A political approach that appeals to ordinary people.");
        map.put("What is a Welfare State?", "A system where the government provides social services.");
        map.put("What is a Campaign?", "A series of organized activities to win elections.");
        map.put("What is Political Propaganda?", "Biased information to influence public opinion.");
        map.put("What is a Lobbyist?", "A person who influences politicians on behalf of groups.");
        map.put("What is a Diplomat?", "A person representing a country in international relations.");
        map.put("What is a Treaty?", "A formal agreement between countries.");
        map.put("What is a Trade Agreement?", "A pact between nations regarding trade policies.");
        map.put("What is a Sanction?", "A penalty imposed on a country to influence its behavior.");
        map.put("What is Foreign Policy?", "A government's strategy in dealing with other nations.");
        map.put("What is Domestic Policy?", "Government actions affecting the internal affairs of a country.");
        map.put("What is a Budget?", "A financial plan for government revenue and spending.");
        map.put("What is an Opposition Party?", "A party that challenges the ruling government.");
        map.put("What is a Speaker of Parliament?", "The official presiding over legislative sessions.");
        map.put("What is a Vote Bank?", "A group of voters loyal to a party or candidate.");
        map.put("What is a Manifesto?", "A document outlining a political party's policies.");
        map.put("What is a Political Debate?", "A discussion where candidates express their views.");
        map.put("What is Gerrymandering?", "Manipulating electoral boundaries for political gain.");
        map.put("What is a Swing State?", "A state where election results are unpredictable.");
        map.put("What is an Impeachment?", "A process to remove a high official from office.");
        map.put("What is Corruption?", "The abuse of power for personal gain.");
        map.put("What is Bureaucracy?", "A system of government officials managing policies.");
        map.put("What is a Political Scandal?", "An event causing public outrage against politicians.");
        map.put("What is a Protest?", "A public demonstration against policies or actions.");
        map.put("What is Civil Disobedience?", "Nonviolent resistance against unjust laws.");
        map.put("What is a Revolution?", "A fundamental change in political power.");
        map.put("What is Martial Law?", "Military control of a government during emergencies.");
        map.put("What is a Coup d'état?", "A sudden overthrow of a government.");
        map.put("What is a Political Refugee?", "A person fleeing persecution due to political beliefs.");
        map.put("What is a Diplomatic Immunity?", "Legal protection for diplomats in foreign countries.");
        map.put("What is an Ambassador?", "A high-ranking official representing a country abroad.");
        map.put("What is a Shadow Cabinet?", "An alternative government prepared by the opposition.");
        map.put("What is Political Polarization?", "Extreme divisions in political opinions.");
        map.put("What is a Think Tank?", "An organization researching political and social issues.");
        map.put("What is a Whistleblower?", "A person exposing corruption or misconduct.");
        map.put("What is a Summit?", "A high-level meeting between leaders.");
        map.put("What is National Security?", "Measures taken to protect a country's safety.");
        map.put("What is a Cyber Attack?", "An attack on digital infrastructure by hackers.");
        map.put("What is a Defense Budget?", "Government spending on military and security.");
        map.put("What is an Autocracy?", "A government where one person has absolute power.");
        map.put("What is an Oligarchy?", "A government ruled by a small group of people.");
        map.put("What is a Theocracy?", "A government based on religious principles.");
        map.put("What is a Secular State?", "A country where religion and government are separate.");
        map.put("What is a Diplomatic Crisis?", "A severe breakdown in relations between countries.");
        map.put("What is Political Asylum?", "Protection given to individuals fleeing persecution.");
        map.put("What is a National Flag?", "A symbol representing a nation's identity.");
        map.put("What is a Political Philosophy?", "A theory about government and society.");
        map.put("What is a Protest Vote?", "A vote against major parties as a form of dissent.");
        map.put("What is a Campaign Finance?", "Money used to fund election campaigns.");
        map.put("What is a Minority Government?", "A government without a full majority in parliament.");
        map.put("What is a Parliamentary Session?", "A period when the legislature meets to discuss laws.");
        map.put("What is a Diplomatic Tension?", "Strained relations between countries.");
        map.put("What is a Peace Treaty?", "An agreement to end a conflict between nations.");
        map.put("What is a Political Dynasty?", "A family that holds political power for generations.");
        map.put("What is a Political Reform?", "Changes made to improve a political system.");
        map.put("What is a Socialist Democracy?", "A mix of socialism and democratic governance.");
        map.put("What is an Economic Policy?", "Government actions to regulate the economy.");
        map.put("What is a Parliamentary Majority?", "When one party holds most seats in parliament.");
        map.put("What is a Civic Duty?", "Responsibilities of citizens towards their country.");
        map.put("What is a Political Realignment?", "A major shift in political party support.");
        map.put("What is a Federal Budget?", "The government's annual financial plan.");
        map.put("What is a Political Ideologue?", "A person strongly committed to a political belief.");
        map.put("What is a National Convention?", "A major meeting of a political party.");
        map.put("What is a Diplomatic Agreement?", "A formal understanding between nations.");
        map.put("What is a Military Alliance?", "A pact between countries for defense purposes.");
        map.put("What is a Political Satire?", "Humor used to criticize political issues.");
        map.put("What is Political Science?", "The study of government and politics.");
        map.put("What is a plebiscite?", "A direct vote by the people on an important issue.");
        map.put("What is a bicameral legislature?", "A legislative body with two houses.");
        map.put("What is a unicameral legislature?", "A legislative body with only one house.");
        map.put("What is a political spectrum?", "A system to classify political ideologies.");
        map.put("What is a political mandate?", "Authority given to a leader by voters.");
        map.put("What is political patronage?", "Giving government jobs in exchange for support.");
        map.put("What is a filibuster?", "A prolonged speech to delay legislative action.");
        map.put("What is a lame-duck period?", "The time between an election and the new government taking office.");
        map.put("What is political apathy?", "Lack of interest in political affairs.");
        map.put("What is a political think tank?", "An organization researching and analyzing policies.");
        map.put("What is political mobilization?", "Encouraging people to participate in politics.");
        map.put("What is political disenfranchisement?", "Denying someone the right to vote.");
        map.put("What is a safe seat?", "A legislative seat that is almost guaranteed to be won by a party.");
        map.put("What is political socialization?", "The process of learning political values and beliefs.");
        map.put("What is a party whip?", "A member responsible for ensuring party discipline in votes.");
        map.put("What is political alignment?", "An individual's political ideology or party preference.");
        map.put("What is gerrymandering?", "Manipulating electoral district boundaries for political advantage.");
        map.put("What is a coalition government?", "A government formed by multiple political parties.");
        map.put("What is a veto?", "The power to reject a proposed law.");
        map.put("What is impeachment?", "A process to remove a public official from office.");
        map.put("What is a political caucus?", "A meeting of party members to select candidates or policies.");
        map.put("What is a referendum?", "A direct vote on a specific political question.");
        map.put("What is a constituency?", "A geographical area represented by an elected official.");
        map.put("What is a primary election?", "An election to select a party’s candidate for a general election.");
        map.put("What is proportional representation?",
                "An electoral system where seats are allocated based on vote share.");
        map.put("What is a swing state?", "A state where election outcomes are unpredictable.");
        map.put("What is a political ideology?", "A set of beliefs about government and society.");
        map.put("What is a political party?", "An organized group seeking to gain political power.");
        map.put("What is an autocracy?", "A system where one person holds absolute power.");
        map.put("What is a theocracy?", "A government based on religious principles.");
        map.put("What is a democracy?", "A system where power is vested in the people.");
        map.put("What is an oligarchy?", "A government controlled by a small group of elites.");
        map.put("What is federalism?", "A system where power is divided between national and state governments.");
        map.put("What is sovereignty?", "Supreme power or authority of a state.");
        map.put("What is diplomacy?", "Managing international relations through negotiation.");
        map.put("What is soft power?", "Influence through culture and diplomacy rather than force.");
        map.put("What is a trade embargo?", "A restriction on trade with a particular country.");
        map.put("What is a welfare state?", "A government that provides social services to citizens.");
        map.put("What is an executive order?", "A directive issued by the head of state without legislative approval.");
        map.put("What is a political lobby?", "An organized group that seeks to influence government decisions.");
        map.put("What is a cabinet?", "A group of advisors to the head of government.");
        map.put("What is a constitution?", "A set of fundamental principles governing a state.");
        map.put("What is judicial review?", "The power of courts to declare laws unconstitutional.");
        map.put("What is a bill of rights?", "A list of fundamental rights protected by the constitution.");
        map.put("What is a minority government?", "A government that does not hold a majority of legislative seats.");
        map.put("What is a vote of no confidence?", "A vote to remove the government from power.");
        map.put("What is a political revolution?",
                "A fundamental change in government, usually through mass mobilization.");
        map.put("What is a political asylum?", "Protection granted to individuals fleeing persecution.");
        map.put("What is populism?", "A political approach that seeks to represent ordinary people against elites.");
        map.put("What is nationalism?", "A belief in promoting national interests and identity.");
        map.put("What is a welfare policy?", "Government programs designed to support citizens' well-being.");
        map.put("What is globalization?", "The increasing interconnectedness of economies and cultures.");
        map.put("What is a trade deficit?", "When a country imports more than it exports.");
        map.put("What is a diplomatic immunity?", "Legal protection for foreign diplomats from prosecution.");
        map.put("What is a political debate?", "A formal discussion between political candidates or representatives.");
        map.put("What is a civil disobedience?", "Peaceful protest against laws considered unjust.");
        map.put("What is a monarchy?", "A government led by a king or queen.");
        map.put("What is anarchy?", "A state without a recognized government.");
        map.put("What is a political coup?", "A sudden and illegal takeover of government power.");
        map.put("What is a progressive tax?", "A tax system where higher incomes are taxed at higher rates.");
        map.put("What is a regressive tax?", "A tax system where lower incomes bear a greater burden.");
        map.put("What is a trade agreement?", "A treaty between countries to regulate trade terms.");
        map.put("What is diplomatic negotiation?", "Discussions between nations to resolve conflicts or agreements.");
        map.put("What is a supermajority?", "A requirement for more than a simple majority to pass legislation.");
        map.put("What is a political watchdog?", "An organization monitoring government actions and accountability.");
        map.put("What is a political dynasty?", "A family maintaining political power for generations.");
        map.put("What is a political manifesto?", "A public declaration of policies and goals by a political party.");
        map.put("What is a grassroots movement?", "A political movement driven by ordinary citizens.");
        map.put("What is a swing vote?", "A vote that can change the outcome of an election.");
        map.put("What is a political polarization?", "The growing ideological divide between political groups.");
        map.put("What is a political endorsement?", "Support given by an individual or group to a candidate.");
        map.put("What is a single-party system?", "A political system where only one party has power.");
        map.put("What is a multi-party system?", "A political system where multiple parties compete for power.");
        map.put("What is a term limit?", "A restriction on how long an official can hold office.");
        map.put("What is a political deadlock?", "A situation where no progress can be made in government decisions.");
        map.put("What is a by-election?", "An election held between general elections to fill a vacant seat.");
        map.put("What is political correctness?", "Avoiding language or actions that may offend social groups.");
        map.put("What is a social contract?", "A theory that government legitimacy is based on the people's consent.");
        map.put("What is a non-governmental organization (NGO)?",
                "An independent organization that operates outside of government control.");
        map.put("What is political exile?", "Forcing someone to leave their home country for political reasons.");
        map.put("What is a power vacuum?", "A situation where no one holds clear political authority.");
        map.put("What is a civil war?", "An armed conflict between groups within a country.");
        map.put("What is an impeachment trial?", "A legal process to determine if an official should be removed.");
        map.put("What is a political assassination?", "The killing of a political leader for political reasons.");
        map.put("What is a presidential pardon?", "A decision to forgive a person convicted of a crime.");
        map.put("What is a political concession?", "A compromise made to resolve a political dispute.");
        map.put("What is an exit poll?", "A survey taken immediately after voters leave the polling station.");
        map.put("What is a populist leader?", "A leader who claims to represent the interests of ordinary people.");

        return map;
    }
}
